# Generated by Django 4.0.1 on 2022-09-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='appuser',
        ),
    ]
